// 'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import NextNProgress from 'nextjs-progressbar';
// import Navbar from '@/components/Navbar'
import dynamic from 'next/dynamic'
// import NextNProgress from 'nextjs-progressbar';



const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false })


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">

        {/* <NextNProgress color='#7e22ce' /> */}
        <body className={inter.className}>
          {/* <NextNProgress /> */}
          <Navbar />
          {children}
          <footer class="bg-white rounded-lg shadow m-4 dark:bg-gray-800">
            <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
              <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" class="hover:underline">Flowbite™</a>. All Rights Reserved.
              </span>
              <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
                <li>
                  <a href="#" class="hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                  <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                </li>
                <li>
                  <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
                </li>
                <li>
                  <a href="#" class="hover:underline">Contact</a>
                </li>
              </ul>
            </div>
          </footer>
        </body>
      </html>
    </>
  )
}
